/*
 * This C++ source file was generated by the Gradle 'init' task.
 */
#ifndef ARDUINO_GRADLE_PROJECT_H
#define ARDUINO_GRADLE_PROJECT_H

#ifdef _WIN32
#define ARDUINO_GRADLE_PROJECT_EXPORT_FUNC __declspec(dllexport)
#else
#define ARDUINO_GRADLE_PROJECT_EXPORT_FUNC
#endif

#include <string>

namespace arduino_gradle_project {
    class Greeter {
        public:
        std::string ARDUINO_GRADLE_PROJECT_EXPORT_FUNC greeting();
    };
}

#endif
