/*
 * This C++ source file was generated by the Gradle 'init' task.
 */

#include "arduino-gradle-project.h"
#include <cassert>

int main() {
    arduino_gradle_project::Greeter greeter;
    assert(greeter.greeting().compare("Hello, World!") == 0);
    return 0;
}
